#ifndef CHEURISTICSTOP_H
#define CHEURISTICSTOP_H

/*  Author:
  Marcin A. Stachura <m.stachura@mchtr.pw.edu.pl>

  Copyright (c) 2015 Marcin A. Stachura

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#include <sstream>

#include "../interfaces/ICStop.h"
#include "../interfaces/ICEvolOptimizer.h"

#include "../indicators/CHyperVolumeIndicator.h"



namespace MEVO {

class CHVStop : public ICStop
{

public:
    /** Constructor */
    CHVStop();

    /** Destructor */
    ~CHVStop();

    /** This function provides calculation of stop condition
        @param _population reference to a last population generated by an algorithm
        @return boolean value of stop criterion (TRUE if the algorithm is to be terminated)
    */
    virtual bool checkStop(ICPopulation* _population);

    /** Description of selected stop criterion
        @return brief description of chosen stop criterion
        */
    virtual const char *getDescription();

    /** sets convergence: a volume of the cubics*/
    void setConvergence(double _c);

    /** gets convergence: a volume of the cubics*/
    double getConvergence();

    /** sets check frequency*/
    void setFrequency(double _f);

    /** gets check grequency*/
    double getFrequency();

    /** function for initializing a stop object
        @param a pointer to an algorithm.
      */
    virtual void init(ICEvolOptimizer* _opt);
protected:
    double FCC;

    unsigned int FFrequency;
    unsigned int FCurrentGeneration;
    ICPopulation* FLastPop;

    void setLastPop(ICPopulation* _population);

    double compareNFeasilbe(ICPopulation* _population);

    double selectOne(ICPopulation *_population);
    bool compareOnes(ICPopulation *_population);


    CHyperVolumeIndicator* FIndicator;

};
}
#endif // CHEURISTICSTOP_H
