#ifndef ICSTOP_H
#define ICSTOP_H

#include "ICPopulation.h"

namespace MEVO {

class ICEvolOptimizer;

//! Basic class interface for stop criterions.
/** Class Interface
       Provides declarations of stop criterion functions
*/
class ICStop
{
public:

    /** virtual destructor */
    virtual ~ICStop() {};

    /** Thisfunction provides calculation of stop criteria
    @param _population reference to a last population generated by an algorithm
    @return boolean value of stop criterion (TRUE if the algorithm is to be terminated)
    */
    virtual bool checkStop(ICPopulation* _population)=0;

    /** Description of selected stop criterion
    @return brief description of chosen stop criterion
    */
    virtual const char *getDescription()=0;

    /** pure virtual function for initializing a stop object
        this function is implemented in inherited classes.
        @param a pointer to an algorithm.
      */
    virtual void init(ICEvolOptimizer* _opt)=0;
};
}
#endif // ICSTOP_H
